# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Performance evaluation of Arctic Weather Satellite data
email: arctic-weather-satellite@smhi.se
description: >- # this means to ignorenewlines until "baseurl:"
  The overarching goal of the project is to perform an early evaluation of
  the Arctic Weather Satellite (AWS) data in the context of the regional
  Numerical Weather Prediction (NWP) modelling systems of the Nordic countries.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arctic-weather-satellite.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
remote_theme: jekyll/minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  # see https://github.com/benbalter/jekyll-relative-links
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
minima:
  skin: dark
  #social_links:
  #  - { platform: twitter, user_url: "https://twitter.com/pytrollorg" }
  #  - { platform: github, user_url: "https://github.com/pytroll" }
header_pages:
  - index.markdown
  - about.md
  - research.md
  - publications.md
  - data_access.md
  - contact.md
  # - new_and_results.md



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
